---
#output: html_document
output:
  github_document:
    html_preview: FALSE
#    code_folding: hide
params:
  prepared_by:
    label: "Prepared by:"
    value: "Richard Martin-Nielsen"
    input: text
title: "COVID-19 in Lithuania: Vaccinations status and incidence, vaccine effectiveness"
---


```{r setup, include=FALSE}

library(vroom)
library(dplyr)
library(lubridate)
library(readxl)
library(tidyr)
library(stringr)
library(httr)
library(jsonlite)
library(ggplot2)

# Set-up output ----
# Figure path on disk = base.dir + fig.path
# Figure URL online = base.url + fig.path
knitr::opts_knit$set(base.dir = stringr::str_c(here::here(), "/docs/"), base.url = "/lt_covid_calcs/") # project root folder
knitr::opts_chunk$set(
	fig.path = stringr::str_c(paste0(paste("images", sep = "/")), "/"),
	message = FALSE,
	warning = FALSE
)

# dataset description: https://open-data-ls-osp-sdg.hub.arcgis.com/datasets/1fd352a1c4534afe8ff87c564c0724c0_0/about
# dataset source:

# The table is intended for monitoring the incidence of infections in four groups of the Lithuanian population: unvaccinated and those who received one / two / three doses of vaccine. The columns in the table describe how many events of each type occurred on a particular day. A total of 17 events are described. Events can only happen to Lithuanian residents who have never been infected before. Event tracking begins on January 1, 2021. The table is aggregated by date, municipality (60 units), gender (2 units), age group (8 units), so each row describes the number of events that occurred on a specific date for a specific age-specific population in a particular municipality.
# An integral part of this table is the auxiliary table "Initial conditions, on 01.01.2021", which describes the number of persons who may become infected at the beginning of 2021-01-01. Only with these two tables is it possible to calculate the frequency of infections (normalized daily number of infections) per day from which preliminary conclusions on the efficacy of vaccines can be drawn.
#
# Column description:
#   date is the day of 2021 on which the events described in the following columns occurred
# municipality - the municipality of the declared place of residence, describing the group of persons participating in the events
# sex - gender describing the group of persons involved in the events: V = men, M = women
# age_gr - an age category that describes the group of people participating in the events
# r0i0 - unvaccinated * who became infected for the first time (event - first infection)
# r0r1 - unvaccinated * who have been vaccinated (event - vaccination)
# r0c0 - unvaccinated * who fell out of the risk of infection ("censored" persons, statistical term, **)
# r0i1 - unvaccinated * who have been vaccinated and become infected for the first time
# r0c1 - unvaccinated * who have been vaccinated and are at risk of becoming infected
# r1i1 - 1 dose vaccinated * who became infected for the first time
# r1r2 - 1 dose vaccinated * who became vaccinated with the second dose
# r1c1 - 1 dose vaccinated * who were at risk of infection ("censored" persons, statistical term, **)
# r1i2 - 1 dose vaccine * who became vaccinated with a second dose and became infected for the first time
# r1c2 - 1 dose vaccine * who became vaccinated with the second dose and were at risk of infection
# r2i2 - 2 doses to be vaccinated * who became infected for the first time
# r2r3 - 2 doses to be vaccinated *, which became the third dose
# r2c2 - 2 doses to be vaccinated * who fell out of the risk of infection ("censored" persons, statistical term, **)
# r2i3 - 2 doses *, which became the third dose and became infected for the first time
# r2c3 - 2 doses * that became the third dose and fell out of the risk of infection
# r3i3 - 3 doses to be vaccinated * who became infected for the first time
# r3c3 - 3 doses to be vaccinated * who fell out of the risk of infection ("censored" persons, statistical term, ***)
# r1i1_mdsv - average number of days since the first vaccination in the r1i1 group (***)
# r2i2_mdsv - average number of days since the second vaccination in the r2i2 group (***)
# r1i1_john - percentage of Janssen vaccine recipients in the r1i1 group (***)
# r2i2_john - percentage of vaccinated Janssen vaccine (as first dose) in the r2i2 group (***)
#
# Column naming logic:
#   first pair of two characters (eg "r1") - what state the persons "leave" during the described event
# second pair of two characters (eg "i2") - what state persons "enter" during the described event
# first character of the character pair (letter):
#   r - 'at risk'; people who may become infected (i.e., this has not happened before)
# i - 'infected'; persons who are infected (first positive diagnostic test)
# c - 'censored'; persons who are not and cannot be infected (**)
# second character of the character pair (number):
#   0 - persons who have not yet been vaccinated on a given day or have been vaccinated very recently (<in the course of 14 days) *
#   1 - persons who have already been vaccinated on a given day 14 days after the first dose or who have received a second dose very recently (<in the course of 14 days) *
#   2 - persons who have been vaccinated for 14 days on a given day since the second dose or who have received a third dose very recently (<14 days) *
#   3 - persons who have already 14 days since the third dose of the vaccine on a given day *
#
#   Detailed logic of the table content explanation in the illustration:
#   illustration
# Footnotes:
#   * The effect of the vaccine is considered to start on day 14 from the actual date of vaccination, so in this table describing the effectiveness of the vaccines, the person is considered unvaccinated on the actual day of the first vaccination (as well as on the thirteenth day after the first vaccination). The same principle applies to the second and third doses of the vaccine: they take effect on the 14th day after the actual date of the vaccination.
# ** unsupervised persons (without 'follow-up', 'censored'), e.g. due to emigration, lost contact, death, etc.
# *** calculated for all municipalities, all genders, all age groups in total (for confidentiality)

# Lentelė yra skirta užsikrėtimų dažniams stebėti keturiose Lietuvos gyventojų grupėse: neskiepytųjų bei skiepytųjų viena/dviem/trim vakcinos dozėmis. Lentelės stulpeliai aprašo, kiek kiekvienos rūšies įvykių įvyko konkrečią dieną. Iš viso yra aprašoma 17 įvykių. Įvykiai gali įvykti tik su iki tol dar niekada neužsikrėtusiais Lietuvos gyventojais. Įvykių stebėjimas prasideda nuo 2021 metų sausio 1 dienos. Lentelė yra agreguota pagal datą, savivaldybę (60 vnt), lytį (2 vnt), amžiaus grupę (8 vnt), tad kiekviena eilutė aprašo įvykių skaičių, kuris nutiko konkrečią datą konkrečios savivaldybės konkrečios lyties konkrečios amžiaus grupės gyventojams.
# Šios lentelės neatsiejama dalis yra pagalbinė lentelė "Pradinės būsenos, 2021-01-01 dieną", kuri aprašo asmenų, galinčių užsikrėsti skaičių 2021-01-01 dienos pradžioje. Tik turint šias abi lenteles įmanoma suskaičiuoti užsikrėtimų dažnį (normalizuotą dieninį užsikrėtimų skaičių) padieniui, iš kurio galima daryti preliminarias išvadas apie vakcinų efektyvumą.
#
# Stulpelių aprašymas:
#   date - 2021 metų diena, kurios metu įvyko tolimesniuose stulpeliuose aprašomi įvykiai
# municipality - deklaruotos gyvenamosios vietos savivaldybė, aprašanti įvykiuose dalyvaujančių asmenų grupę
# sex - lytis, aprašanti įvykiuose dalyvaujančių asmenų grupę: V = vyrai, M = moterys
# age_gr - amžiaus kategorija, aprašanti įvykiuose dalyvaujančių asmenų grupę
# r0i0 - neskiepyti*, kurie pirmą kartą tapo užsikrėtusiais (įvykis - pirmas užsikrėtimas)
# r0r1 - neskiepyti*, kurie tapo paskiepytais (įvykis - paskiepijimas)
# r0c0 - neskiepyti*, kurie iškrito iš rizikos užsikrėsti ("cenzūruoti" asmenys, statistikos terminas, **)
# r0i1 - neskiepyti*, kurie tapo paskiepytais ir pirmą kartą tapo užsikrėtusiais
# r0c1 - neskiepyti*, kurie tapo paskiepytais ir iškrito iš rizikos užsikrėsti
# r1i1 - 1 doze skiepyti*, kurie pirmą kartą tapo užsikrėtusiais
# r1r2 - 1 doze skiepyti*, kurie tapo paskiepytais antra doze
# r1c1 - 1 doze skiepyti*, kurie iškrito iš rizikos užsikrėsti ("cenzūruoti" asmenys, statistikos terminas, **)
# r1i2 - 1 doze skiepyti*, kurie tapo paskiepytais antra doze ir pirmą kartą tapo užsikrėtusiais
# r1c2 - 1 doze skiepyti*, kurie tapo paskiepytais antra doze ir iškrito iš rizikos užsikrėsti
# r2i2 - 2 dozėm skiepyti*, kurie pirmą kartą tapo užsikrėtusiais
# r2r3 - 2 dozėm skiepyti*, kurie tapo paskiepytais trečia doze
# r2c2 - 2 dozėm skiepyti*, kurie iškrito iš rizikos užsikrėsti ("cenzūruoti" asmenys, statistikos terminas, **)
# r2i3 - 2 dozėm skiepyti*, kurie tapo paskiepytais trečia doze ir pirmą kartą tapo užsikrėtusiais
# r2c3 - 2 dozėm skiepyti*, kurie tapo paskiepytais trečia doze ir iškrito iš rizikos užsikrėsti
# r3i3 - 3 dozėm skiepyti*, kurie pirmą kartą tapo užsikrėtusiais
# r3c3 - 3 dozėm skiepyti*, kurie iškrito iš rizikos užsikrėsti ("cenzūruoti" asmenys, statistikos terminas, ***)
# r1i1_mdsv - vidutinis dienų skaičius praėjęs nuo pirmo skiepo r1i1 asmenų grupėje (***)
# r2i2_mdsv - vidutinis dienų skaičius praėjęs nuo antro skiepo r2i2 asmenų grupėje (***)
# r1i1_john - vakcinuotųjų "Janssen" vakcina procentas r1i1 asmenų grupėje (***)
# r2i2_john - vakcinuotųjų "Janssen" vakcina (kaip pirma doze) procentas r2i2 asmenų grupėje (***)
#
# Stulpelių pavadinimo sudarymo logika:
#   pirma dviejų simbolių pora (pvz "r1") - iš kokios būsenos asmenys "išeina" aprašomo įvykio metu
# antra dviejų simbolių pora (pvz "i2") - į kokią būseną asmenys "įeina" aprašomo įvykio metu
# pirmas simbolių poros simbolis (raidė):
#   r - 'at risk'; asmenys, kurie gali užsikrėsti (t.y., tai dar neatsitiko anksčiau)
# i - 'infected'; asmenys, kurie yra užsikrėtę (pirmas teigiamas diagnostinis testas)
# c - 'censored'; asmenys, kurie nėra užsikrėtę ir negali užsikrėsti (**)
# antras simbolių poros simbolis (skaičius):
#   0 - asmenys, kurie konkrečią dieną dar yra neskiepyti arba yra paskiepyti labai neseniai (<14 d. eigoje) *
#   1 - asmenys, kuriems konkrečią dieną nuo pirmos skiepo dozės jau yra praėję 14 dienų, arba jie yra paskiepyti antra doze labai neseniai (<14 d. eigoje) *
#   2 - asmenys, kuriems konkrečią dieną nuo antros skiepo dozės jau yra praėję 14 dienų, arba jie yra paskiepyti trečia doze labai neseniai (<14 d. eigoje) *
#   3 - asmenys, kuriems konkrečią dieną nuo trečios skiepo dozės jau yra praėję 14 dienų *
#
#   Detali lentelės turinio paaiškinimo logika iliustracijoje:
#   iliustracija
# Išnašos:
#   * laikoma, kad vakcinos efektas prasideda 14-ą dieną nuo faktinės skiepijimo datos, tad šioje lentelėje, aprašančioje vakcinų efektyvumą, asmuo faktinę pirmo skiepo dieną (o taip pat ir tryliktą dieną po pirmo skiepo) yra laikomas nevakcinuotu. Toks pat principas taikomas ir antrai bei trečiai skiepo dozėms: jos įsigalioja 14-ą dieną nuo faktinės skiepijimo datos.
# ** nebestebimi asmenys (be 'follow-up', 'censored'), pvz. dėl emigracijos, prarasto kontakto, mirties ir pan.
# *** apskaičiuota visoms savivaldybėms, visom lytims, visoms amžiaus grupėms bendrai (dėl konfidencialumo)

download_restful <- function (api_call = "",
                              data_filter = function(x) { return(x) }) {
  if(str_length(api_call) == 0) {
    message("Empty api_call")
    return(NULL)
  }
  get_data <- GET(api_call)

  get_content <- content(get_data, "text")

  get_json <- fromJSON(get_content, flatten = TRUE)

  get_df <- as.data.frame(get_json$features)

  result_offset <- dim(get_df)
  result_offset <- result_offset[1]

  get_df <- data_filter(get_df)

  page <- 1
  done_download <- FALSE
  supp_data <- get_data

  rm("get_data", "get_content", "get_json")

  while (!done_download && supp_data$status_code == 200) {
    offset <- result_offset * page
    page <- page + 1
    supp_api_call <-
      paste(api_call, "&resultOffset=", sprintf("%d", offset), sep = "")
    supp_data <- GET(supp_api_call)
    message( ".", appendLF = FALSE)

    supp_content <- content(supp_data, "text")
    supp_json <- fromJSON(supp_content, flatten = TRUE)
    supp_df <- as.data.frame(supp_json$features) %>%
      data_filter()
    row_count <- dim(supp_json$features)
    row_count <- row_count[1]

    if (!hasName(supp_json, "exceededTransferLimit")) {
      message(
        "\nDownload complete"
      )
      done_download <- TRUE
    }
    if (supp_data$status_code == 200) {
      get_df <- rbind(get_df, supp_df)
    } else {
      message("\nDownload finished with unexpected status code",
              supp_data$status_code
      )
      break
    }
  }
  return(get_df)
}

lt_vacc_eff_data <- download_restful(
  api_call = "https://services3.arcgis.com/MF53hRPmwfLccHCj/arcgis/rest/services/COVID_u%C5%BEsikr%C4%97timai_tarp_vakcinuot%C5%B3_ir_nevakcinuot%C5%B3/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json" # nolint
) %>%
  rename_with(~ gsub("attributes.","", .x)) %>%
  mutate(date = as_date(as_datetime(date / 1000)))
```


```{r data_manipulation, echo=FALSE}

lt_natl_ve_data <- tibble(lt_vacc_eff_data) %>%
  #select(-object_id) %>%
  group_by(date, sex, age_gr) %>%
  summarise(across(matches('[icr]\\d[icr]\\d$'), ~ sum(.x, na.rm=TRUE))) %>%
  ungroup()

lt_pop <- 2795680

# library(covidregionaldata)
# get_regional_data("Lithuania") %>% select(cases_new,date) %>% filter(date < ymd("2021-01-01")) %>% summarise(cases=sum(cases_new))
cases_in_2020 <- 147984

r0_init <- lt_pop - cases_in_2020

infection_comparisons <- lt_natl_ve_data %>%
  # select(date, age_gr, sex,
  #        r0i0, r1i1, r2i2, r3i3, # infection events
  #        r1r2, r2r3  # vaccination transitions
  #        ) %>%
  #filter(date == "2021-10-18") %>%
  group_by(date) %>%
  #select(-date)%>%
  summarise(across(matches('[icr]\\d[icr]\\d$'), ~ sum(.x, na.rm=TRUE))) %>%
  mutate(partially = (r1i1+r1i2) / (r0i0+r0i1+r1i1+r1i2+r2i2+r2i3+r3i3),
         fully = (r2i2+r2i3+r3i3) / (r0i0+r0i1+r1i1+r1i2+r2i2+r2i3+r3i3)) %>%
  ungroup() %>%
  # calculate populations in each category
  mutate(
    censored = r0c0+r0c1+r1c1+r1c2+r2c2+r2c3+r3c3, # per day
    infected = r0i0+r0i1+r1i1+r1i2+r2i2+r2i3+r3i3, # per day
    r_pop = r0_init - cumsum(censored + infected),
    r_pop_r1 = cumsum(r0r1-r1r2-r1i1-r1c1-r1i2-r1c2),
    r_pop_r2 = cumsum(r1r2-r2r3-r2i2-r2c2-r2i3-r2c3),
    r_pop_r3 = cumsum(r2r3-r3c3-r3i3),
    r_pop_r0 = r0_init - r_pop_r1 - r_pop_r2 - r_pop_r3) %>%
  # fractions of each population infected
  mutate(
    i_frac_r0 = (r0i0+r0i1) / r_pop_r0,
    i_frac_r1 = (r1i1+r1i2) / r_pop_r1,
    i_frac_r2 = (r2i2+r2i3) / r_pop_r2,
    i_frac_r3 = (r3i3) / r_pop_r3
  ) %>%
  mutate(
    ve_vs_r0_r1 =  (i_frac_r0 - i_frac_r1)/i_frac_r0,
    ve_vs_r0_r2 = (i_frac_r0 - i_frac_r2)/i_frac_r0, #i_frac_r2 / i_frac_r0,
    ve_vs_r0_r3 = if_else(r_pop_r3 != 0,(i_frac_r0 - i_frac_r3)/i_frac_r0, NA_real_)
  ) %>%
  pivot_longer(
    cols = !c("date"),
    values_to = "count",
    names_to = "event")
```


```{r cases_graph_contributions}
infection_comparisons %>%
  group_by(event) %>%
  mutate(pc_cases_7d_mean = zoo::rollmean(count,k=7, fill=0, align="right") ) %>%
  ungroup() %>%
  filter(event %in% c("r0i0", "r0i1", "r1i1", "r1i2", "r2i2", "r2i3", "r3i3")) %>%
  filter(date > ymd("2021-01-7")) %>%
  ggplot(aes(x = date, y=pc_cases_7d_mean, colour=event)) +
  theme_minimal() +
  geom_line(size=1) +
  #scale_fill_brewer(palette = "Set2") +
  scale_colour_viridis_d(name = "Individual\nvaccination\nstatus",
                         breaks = c("r0i0", "r0i1", "r1i1", "r1i2", "r2i2", "r2i3", "r3i3"),
                         labels = c("Unvaccinated or\nless than 14d\nafter 1st dose",
                                    "14d after\n1st dose",
                                    "14+d after\n1st dose",
                                    "14d after\n2nd dose",
                                    "14+d after\n2nd dose",
                                    "14d after\n3rd dose",
                                    "14+d after\n3rd dose")) +
  theme(legend.position = "bottom") +
  scale_y_continuous(sec.axis = sec_axis(~ .)) +
  labs(title="Lithuania - COVID-19 cases by vaccination status",
       subtitle="7 day rolling average",
       y="New cases",
       x="Date",
       caption="Richard Martin-Nielsen | Data: Office of Statistics Portal osp.stat.gov.lt") +
  scale_x_date()
```

```{r cases_graph_fractions}
infection_comparisons %>%
  group_by(event) %>%
  mutate(pc_cases_7d_mean = zoo::rollmean(count,k=7, fill=0, align="right") ) %>%
  ungroup() %>%
  filter(event %in% c("partially", "fully")) %>%
  #filter(date > ymd("2020-11-01")) %>%
  ggplot(aes(x = date, y=pc_cases_7d_mean, colour=event)) +
  theme_minimal() +
  geom_line(size=1) +
  #scale_fill_brewer(palette = "Set2") +
  scale_colour_viridis_d(name = "Vaccination status",
                         breaks = c("partially", "fully"),
                         labels = c("Partially", "Fully")) +
  theme(legend.position = "bottom") +
  scale_y_continuous( labels = scales::percent,
                      sec.axis = sec_axis(~ ., labels = scales::percent)) +
  labs(title="Lithuania - COVID-19 cases by vaccination status",
       subtitle="7 day rolling average as fraction of total infections",
       y="New cases",
       x="Date",
       caption="Richard Martin-Nielsen | Data: Office of Statistics Portal osp.stat.gov.lt") +
  scale_x_date()
```

```{r cases_by_status_proportional}
infection_comparisons %>%
  group_by(event) %>%
  mutate(pc_cases_7d_mean = zoo::rollmean(count,k=7, fill=0, align="right")*1000 ) %>%
  ungroup() %>%
  filter(event %in% c("i_frac_r0", "i_frac_r1", "i_frac_r2", "i_frac_r3")) %>%
  filter(date > ymd("2021-03-01")) %>%
  ggplot(aes(x = date, y=pc_cases_7d_mean, colour=event)) +
  theme_minimal() +
  geom_line(size=1) +
  #scale_fill_brewer(palette = "Set2") +
  scale_colour_viridis_d(name = "Vaccination status (14 days after...)",
                         breaks = c("i_frac_r0", "i_frac_r1", "i_frac_r2", "i_frac_r3"),
                         labels = c("Unvaccinated",
                                    "First dose",
                                    "Second dose",
                                    "Booster")) +
  theme(legend.position = "bottom") +
  scale_y_continuous(sec.axis = sec_axis(~ .)) +
  labs(title="Lithuania - COVID-19 cases by vaccination status",
       subtitle="7 day average cases per 1000 population with that status",
       y="New cases",
       x="Date",
       caption="Richard Martin-Nielsen | Data: Office of Statistics Portal osp.stat.gov.lt") +
  scale_x_date()
```

```{r vaccine_effectiveness_7d}
infection_comparisons %>%
  group_by(event) %>%
  mutate(pc_cases_7d_mean = zoo::rollmean(count,k=7, fill=0, align="right") ) %>%
  ungroup() %>%
  filter(event %in% c("ve_vs_r0_r1", "ve_vs_r0_r2", "ve_vs_r0_r3")) %>%
  filter(date > ymd("2021-03-01")) %>%
  filter(pc_cases_7d_mean<1) %>%
  ggplot(aes(x = date, y=pc_cases_7d_mean, colour=event)) +
  theme_minimal() +
  geom_line(size=1) +
  #scale_fill_brewer(palette = "Set2") +
  scale_colour_viridis_d(name = "Vaccination status (14 days after...)",
                         breaks = c("ve_vs_r0_r1", "ve_vs_r0_r2", "ve_vs_r0_r3"),
                         labels = c("First dose",
                                    "Second dose",
                                    "Booster")) +
  theme(legend.position = "bottom") +
  scale_y_continuous(
    sec.axis = sec_axis(
      ~ .,
      breaks = seq(from = 0, to = 1, by = 0.1),
      labels = scales::percent),
    limits = c(0,1),
    breaks = seq(from = 0, to = 1, by = 0.1),
    #limits = c(0,15),
    labels = scales::percent,
    oob = scales::oob_censor) +
  labs(title="Lithuania - COVID-19 vaccine effectiveness by vaccination status",
       subtitle="7 day mean compared with unvaccinated",
       y="Incidence within population relative to unvaccinated",
       x="Date",
       caption="Richard Martin-Nielsen | Data: Office of Statistics Portal osp.stat.gov.lt") +
  scale_x_date()
```

```{r vaccine_effectiveness_14d}

infection_comparisons %>%
  group_by(event) %>%
  mutate(pc_cases_14d_mean = zoo::rollmean(count,k=14, fill=0, align="right") ) %>%
  ungroup() %>%
  filter(event %in% c("ve_vs_r0_r1", "ve_vs_r0_r2", "ve_vs_r0_r3")) %>%
  filter(date > ymd("2021-03-01")) %>%
  filter(pc_cases_14d_mean<1) %>%
  ggplot(aes(x = date, y=pc_cases_14d_mean, colour=event)) +
  theme_minimal() +
  geom_line(size=1) +
  #scale_fill_brewer(palette = "Set2") +
  scale_colour_viridis_d(name = "Vaccination status (14 days after...)",
                         breaks = c("ve_vs_r0_r1", "ve_vs_r0_r2", "ve_vs_r0_r3"),
                         labels = c("First dose",
                                    "Second dose",
                                    "Booster")) +
  theme(legend.position = "bottom") +
  scale_y_continuous(
    sec.axis = sec_axis(
      ~ .,
      breaks = seq(from = 0, to = 1, by = 0.1),
      labels = scales::percent),
    limits = c(0,1),
    breaks = seq(from = 0, to = 1, by = 0.1),
    #limits = c(0,15),
    labels = scales::percent,
    oob = scales::oob_censor) +
  labs(title="Lithuania - COVID-19 vaccine effectiveness by vaccination status",
       subtitle="14 day mean",
       y="Vaccine effectiveness",
       x="Date",
       caption="Richard Martin-Nielsen | Data: Office of Statistics Portal osp.stat.gov.lt") +
  scale_x_date()
```
